apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-postgres-pod
  labels:
    name: {{ .Release.Name }}-postgres-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgres
      image: {{.Values.postgres.image}}
      ports:
        - containerPort: 5432
      env: 
        - name: POSTGRES_USER
          value: {{.Values.postgres.username}}
        - name: POSTGRES_PASSWORD
          value: {{.Values.postgres.password}}