apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{.Release.Name}}-postgres-deploy
  labels:
    name: {{.Release.Name}}-postgres-deploy 
    app: demo-voting-app
spec:
  replicas: {{.Values.postgres.replicas}}
  template:
    metadata:
      name: {{.Release.Name}}-postgres-pod
      labels:
        name: {{.Release.Name}}-postgres-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: {{.Values.postgres.image}}
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_USER
              value: {{.Values.postgres.username}}
            - name: POSTGRES_PASSWORD
              value: {{.Values.postgres.password}}
  selector:
    matchLabels:
      name: {{.Release.Name}}-postgres-pod
      app: demo-voting-app

