apiVersion: v1 
kind: Service
metadata:
  name: db
  labels:
    name: {{.Release.Name}}-postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: {{.Release.Name}}-postgres-pod
    app: demo-voting-app
