apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{.Release.Name}}-redis-deploy
  labels:
    name: {{.Release.Name}}-redis-deploy 
    app: demo-voting-app
spec:
  replicas: 1
  template:
    metadata:
      name: {{.Release.Name}}-redis-pod
      labels:
        name: {{.Release.Name}}-redis-pod
        app: demo-voting-app
    spec:
      containers:
        - name: redis
          image: {{.Values.redis.image}}
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      name: {{.Release.Name}}-redis-pod
      app: demo-voting-app

