apiVersion: v1 
kind: Service
metadata:
  name: redis
  labels:
    name: {{.Release.Name}}-redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: {{.Release.Name}}-redis-pod
    app: demo-voting-app
