apiVersion: v1 
kind: Service
metadata:
  name: {{.Release.Name}}-result-service
  labels:
    name: {{.Release.Name}}-result-service
    app: demo-voting-app
spec:
  type: {{.Values.resultapp.type}}
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: {{.Release.Name}}-result-app-pod
    app: demo-voting-app
