apiVersion: v1 
kind: Service
metadata:
  name: {{.Release.Name}}-voting-service
  labels:
    name: {{.Release.Name}}-voting-service
    app: demo-voting-app
spec:
  type: {{.Values.voteapp.type}}
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: {{.Release.Name}}-voting-app-pod
    app: demo-voting-app
